import mongoose from 'mongoose';

const userSchema = new mongoose.Schema({
name: {type: String,required: true},

email:{type: String, required: true},

email_verified: {type: Boolean,required: true},

phone_number: {type: Number},

address_1: {type: String},

address_2: {type: String },

city: { type: String},

state:{type: String},

province:{type: String},

zip: {type: Number },

portal :{type:Number} ,

country: {type: String,enum:[Afghanistan,
    Albania,
    Algeria,
    Andorra,
    Angola,
    Antigua & Deps,
    Argentina,
    Armenia,
    Australia,
    Austria,
    Azerbaijan,
    ,
    Bahrain,
    Bangladesh,
    Barbados,
    Belarus,
    Belgium,
    Belize,
    Benin,
    Bhutan,
    Bolivia,
    Bosnia_Herzegovina,
    Botswana,
    Brazil,
    Brunei,
    Bulgaria,
    Burkina,
    Burundi,
    Cambodia,
    Cameroon,
    Canada,
    Cape_Verde,
    Central_African_Rep,
    Chad,
    Chile,
    China,
    Colombia,
    Comoros,
    Congo,
    Congo_Democratic_Rep,
    Costa_Rica,
    Croatia,
    Cuba,
    Cyprus,
    Czech_Republic,
    Denmark,
    Djibouti,
    Dominica,
    Dominican_Republic,
    East_Timor,
    Ecuador,
    Egypt,
    El_Salvador,
    Equatorial_Guinea,
    Eritrea,
    Estonia,
    Ethiopia,
    Fiji,
    Finland,
    France,
    Gabon,
    Gambia,
    Georgia,
    Germany,
    Ghana,
    Greece,
    Grenada,
    Guatemala,
    Guinea,
    Guinea_Bissau,
    Guyana,
    Haiti,
    Honduras,
    Hungary,
    Iceland,
    India,
    Indonesia,
    Iran,
    Iraq,
    Ireland_Republic,
    Israel,
    Italy,
    Ivory_Coast,
    Jamaica,
    Japan,
    Jordan,
    Kazakhstan,
    Kenya,
    Kiribati,
    Korea_North,
    Korea_South,
    Kosovo,
    Kuwait,
    Kyrgyzstan,
    Laos,
    Latvia,
    Lebanon,
    Lesotho,
    Liberia,
    Libya,
    Liechtenstein,
    Lithuania,
    Luxembourg,
    Macedonia,
    Madagascar,
    Malawi,
    Malaysia,
    Maldives,
    Mali,
    Malta,
    Marshall_Islands,
    Mauritania,
    Mauritius,
    Mexico,
    Micronesia,
    Moldova,
    Monaco,
    Mongolia,
    Montenegro,
    Morocco,
    Mozambique,
    Myanmar(Burma),
    Namibia,
    Nauru,
    Nepal,
    Netherlands,
    New_Zealand,
    Nicaragua,
    Niger,
    Nigeria,
    Oman,
    Norway,
    Palau,
    Pakistan,
    Papua_New_Guinea,
    Panama,
    Peru,
    Paraguay,
    Poland,
    Philippines,
    Qatar,
    Portugal,
    Russian_Federation,
    Romania,
    St_Kitts & Nevis,
    Rwanda,
    Saint_Vincent & the_Grenadines,
    St_Lucia,
    San_Marino,
    Samoa,
    Saudi_Arabia,
    Sao_Tome & Principe,
    Serbia,
    Senegal,
    Sierra_Leone,
    Seychelles,
    Slovakia,
    Singapore,
    Solomon_Islands,
    Slovenia,
    South_Africa,
    Somalia,
    Spain,
    South_Sudan,
    Sudan,
    Sri_Lanka,
    Swaziland,
    Suriname,
    Switzerland,
    Sweden,
    Taiwan,
    Syria,
    Tanzania,
    Tajikistan,
    Togo,
    Thailand,
    Trinidad & Tobago,
    Tonga,
    Turkey,
    Tunisia,
    Tuvalu,
    Turkmenistan,
    Ukraine,
    Uganda,
    United_Kingdom,
    United_Arab_Emirates,
    Uruguay,
    United_States,
    Vanuatu,
    Uzbekistan,
    Venezuela,
    Vatican_City,
    Yemen,
    Vietnam,
    Zambia,
    Zimbabwe]}
})

const client = mongoose.model('user', userSchema);

export default client;
